# Generated by Django 5.1.4 on 2025-01-11 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Fermangiz nomi')),
                ('location', models.CharField(max_length=255, verbose_name='Manzil')),
                ('area_size', models.FloatField(verbose_name="Maydon o'lchami (gektar)")),
                ('owner', models.CharField(max_length=255, verbose_name='Egasining ismi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="So'nggi yangilanish")),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Asbob nomi')),
                ('model', models.CharField(max_length=100, verbose_name='Modeli')),
                ('purchased_at', models.DateTimeField(verbose_name='Sotib olingan sana')),
                ('last_maintenance', models.DateField(verbose_name="So'nggi texnik xizmat sanasi")),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='farm_app.farm', verbose_name="Fermaga bog'lanish")),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familyasi')),
                ('role', models.CharField(max_length=100, verbose_name='Lavozimi')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Oylik maosh')),
                ('hired_at', models.DateTimeField(verbose_name='Ishga qabul qilingan sana')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='farm_app.farm', verbose_name="Fermaga bog'lanish")),
            ],
        ),
        migrations.CreateModel(
            name='FarmExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(max_length=100, verbose_name='Xarajat turi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdori')),
                ('date', models.DateTimeField(verbose_name='Xarajat sanasi')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='farm_app.farm', verbose_name="Fermaga bog'lanish")),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mahsulot nomi')),
                ('quantity', models.FloatField(verbose_name='Miqdori (tonna)')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birlik narxi')),
                ('harvested_at', models.DateTimeField(verbose_name='Hosil olingan sana')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='farm_app.farm', verbose_name="Fermaga bog'lanish")),
            ],
        ),
        migrations.CreateModel(
            name='FarmIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Daromad miqdori')),
                ('date', models.DateTimeField(verbose_name='Daromad sanasi')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='farm_app.farm', verbose_name="Fermaga bog'lanish")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='farm_app.product', verbose_name='Mahsulot')),
            ],
        ),
    ]
