# Generated by Django 5.1.4 on 2025-01-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Xodim', 'verbose_name_plural': 'Xodimlar'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Asbob', 'verbose_name_plural': 'Asboblar'},
        ),
        migrations.AlterModelOptions(
            name='farm',
            options={'verbose_name': 'Fermangiz', 'verbose_name_plural': 'Fermalar'},
        ),
        migrations.AlterModelOptions(
            name='farmexpense',
            options={'verbose_name': 'Xarajat', 'verbose_name_plural': 'Xarajatlar'},
        ),
        migrations.AlterModelOptions(
            name='farmincome',
            options={'verbose_name': 'Daromad', 'verbose_name_plural': 'Daromadlar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
    ]
