# Generated by Django 5.1.4 on 2025-01-19 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0005_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
    ]
