# Generated by Django 5.1.4 on 2025-01-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ism familiya')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefon raqam')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('is_checked', models.BooleanField(default=False, verbose_name="O'qilganmi?")),
            ],
        ),
    ]
