# Generated by Django 5.1.4 on 2025-01-16 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Xabar', 'verbose_name_plural': 'Xabarlar'},
        ),
    ]
